### PR TITLE
-1.1 incorrectly parsed a NegateInt(Float) instead of Float

### PR DESCRIPTION
**Pull request by CrowdHailer**
This is a breaking change but I think it's worth fixing

### CODE REVIEW

**Comment by lpil** [comment]
What's the motivation for this change?

**Comment by CrowdHailer** [comment]
`-1.0` is valid. So it's not just used for ints

**Comment by lpil** [comment]
That's a float literal, the `-` operator is valid only for ints.

**Comment by CrowdHailer** [comment]
glance parses `-1.0` as `NegInt(Float)`

**Comment by lpil** [comment]
That's a bug then I'm afraid.

**Comment by CrowdHailer** [comment]
Screenshot 2024-01-25 at 13 18 26
it works the same in latest gleam,

**Comment by lpil** [comment]
That's a float literal, the int negation operation is not used there.

**Comment by lpil** [comment]
OK making an issue for this! Thank you

**Pull request closed without merging**
